CREATE TABLE dwd.`dwd_千川_素材m` (
    `来源` VARCHAR(50),
    `千川UID` VARCHAR(100),
    `抖音UID` VARCHAR(100),
    `日期` DATETIME,
    `时间` DATETIME,
    `素材ID` VARCHAR(100),
    `创建时间` DATETIME,
    `投放时间` DATETIME,
    `全域素材视频类型` VARCHAR(100),
    `全域素材视频名称` TEXT,
    `消耗` DECIMAL(18, 2),
    `展现` DECIMAL(18, 2),
    `点击` DECIMAL(18, 2),
    `订单数` DECIMAL(18, 2),
    `成交金额` DECIMAL(18, 2),
    `用户实际支付金额` DECIMAL(18, 2),
    `净成交订单数` DECIMAL(18, 2),
    `净成交金额` DECIMAL(18, 2),
    `用户实际支付净成交金额` DECIMAL(18, 2),
    `追投消耗` DECIMAL(18, 2),
    `追投展现` DECIMAL(18, 2),
    `追投点击` DECIMAL(18, 2),
    `追投订单数` DECIMAL(18, 2),
    `追投成交金额` DECIMAL(18, 2),
    `追投用户实际支付金额` DECIMAL(18, 2),
    `视频播放数` DECIMAL(18, 2),
    `2秒播放率` CHAR(10),
    `3秒播放率` CHAR(10),
    `5秒播放率` CHAR(10),
    `10秒播放率` CHAR(10),
    `视频完播数` DECIMAL(18, 2),
    `粉丝数` DECIMAL(18, 2),
    `评论数` DECIMAL(18, 2),
    `点赞数` DECIMAL(18, 2),
    `1小时内退款订单数` DECIMAL(18, 2),
    `1小时内退款金额` DECIMAL(18, 2),
    `7日结算订单数` DECIMAL(18, 2),
    `7日结算金额` DECIMAL(18, 2),
    -- PRIMARY KEY (`千川UID`, `抖音UID`, `时间`),
    INDEX (千川UID, 抖音UID,时间)
);
TRUNCATE TABLE dwd.`dwd_千川_素材m`;

INSERT INTO dwd.`dwd_千川_素材m`
SELECT
'素材-直播间画面' 来源 ,
`千川UID`,
主播ID 抖音UID,
STR_TO_DATE(统计日期, '%Y-%m-%d 00:00:00') AS 日期,
STR_TO_DATE(时间, '%Y-%m-%d %H:%i:%s') AS 时间,
'' 素材ID ,
NULL AS 创建时间,
NULL AS 投放时间,
'' 全域素材视频类型,
'' 全域素材视频名称,
CAST(REPLACE(`整体消耗(元)`, ',', '') AS DECIMAL(18,2)) AS 消耗,
CAST(REPLACE(`整体展示次数`, ',', '') AS DECIMAL(18,2)) AS 展现,
CAST(REPLACE(`整体点击次数`, ',', '') AS DECIMAL(18,2)) AS 点击,
CAST(REPLACE(`整体成交订单数`, ',', '') AS DECIMAL(18,2)) AS 订单数,
CAST(REPLACE(`整体成交金额(含优惠券/补贴)`, ',', '') AS DECIMAL(18,2)) AS 成交金额,
CAST(REPLACE(`用户实际支付金额`, ',', '') AS DECIMAL(18,2)) AS 用户实际支付金额,
CAST(REPLACE(`1小时净成交订单数`, ',', '') AS DECIMAL(18,2)) AS 净成交订单数,
CAST(REPLACE(`1小时净成交金额`, ',', '') AS DECIMAL(18,2)) AS 净成交金额,
CAST(REPLACE(`用户实际支付净成交金额(1小时)`, ',', '') AS DECIMAL(18,2)) AS 用户实际支付净成交金额,
CAST(REPLACE(`追投调控消耗(元)`, ',', '') AS DECIMAL(18,2)) AS 追投消耗,
CAST(REPLACE(`追投调控展示次数`, ',', '') AS DECIMAL(18,2)) AS 追投展现,
CAST(REPLACE(`追投调控点击次数`, ',', '') AS DECIMAL(18,2)) AS 追投点击,
CAST(REPLACE(`追投调控成交订单数`, ',', '') AS DECIMAL(18,2)) AS 追投订单数,
CAST(REPLACE(`追投调控成交金额(含优惠券)`, ',', '') AS DECIMAL(18,2)) AS 追投成交金额,
CAST(REPLACE(`追投调控用户实际支付金额`, ',', '') AS DECIMAL(18,2)) AS 追投用户实际支付金额,
0 视频播放数,
'0' 2秒播放率,
'0' 3秒播放率,
'0' 5秒播放率,
'0' 10秒播放率,
'0' 视频完播数,
CAST(REPLACE(`新增粉丝数`, ',', '') AS DECIMAL(18,2)) AS 粉丝数,
CAST(REPLACE(`直播间评论次数`, ',', '') AS DECIMAL(18,2)) AS 评论数,
CAST(REPLACE(`直播间点赞次数`, ',', '') AS DECIMAL(18,2)) AS 点赞数,
CAST(REPLACE(`1小时内退款订单数`, ',', '') AS DECIMAL(18,2)) AS 1小时内退款订单数,
CAST(REPLACE(`1小时内退款金额`, ',', '') AS DECIMAL(18,2)) AS 1小时内退款金额,
CAST(REPLACE(`7日结算订单数`, ',', '') AS DECIMAL(18,2)) AS 7日结算订单数,
CAST(REPLACE(`7日结算金额`, ',', '') AS DECIMAL(18,2)) AS 7日结算金额
FROM ods.`ods_千川素材_直播画面_m`
-- WHERE 整体展示次数>0 OR `整体消耗(元)`>0
UNION ALL
-- INSERT INTO dwd.`dwd_千川_素材m` 
SELECT
'素材-视频' 来源 ,
`千川UID`,
 抖音UID,
STR_TO_DATE(日期,'%Y-%m-%d 00:00:00') AS `日期`,
STR_TO_DATE(时间,'%Y-%m-%d %H:%i:%s') AS `时间`,
-- STR_TO_DATE(日期, '%Y-%m-%d') AS 日期,
-- STR_TO_DATE(时间, '%Y-%m-%d %H:%i:%s') AS 时间,
素材ID ,
STR_TO_DATE(NULLIF(创建时间, '-'), '%Y-%m-%d %H:%i:%s') AS `创建时间`,
STR_TO_DATE(NULLIF(投放时间, '-'), '%Y-%m-%d %H:%i:%s') AS `投放时间`,
-- STR_TO_DATE(创建时间, '%Y-%m-%d %H:%i:%s') AS 创建时间,
-- STR_TO_DATE(投放时间, '%Y-%m-%d %H:%i:%s') AS 投放时间,
全域素材视频类型,
全域素材视频名称,
CAST(REPLACE(`整体消耗`, ',', '') AS DECIMAL(18,2)) AS 消耗,
CAST(REPLACE(`整体展现次数`, ',', '') AS DECIMAL(18,2)) AS 展现,
CAST(REPLACE(`整体点击次数`, ',', '') AS DECIMAL(18,2)) AS 点击,
CAST(REPLACE(`整体成交订单数`, ',', '') AS DECIMAL(18,2)) AS 订单数,
CAST(REPLACE(`整体成交金额`, ',', '') AS DECIMAL(18,2)) AS 成交金额,
CAST(REPLACE(`用户实际支付金额`, ',', '') AS DECIMAL(18,2)) AS 用户实际支付金额,
CAST(REPLACE(`净成交订单数`, ',', '') AS DECIMAL(18,2)) AS 净成交订单数,
CAST(REPLACE(`净成交金额`, ',', '') AS DECIMAL(18,2)) AS 净成交金额,
CAST(REPLACE(`用户实际支付净成交金额`, ',', '') AS DECIMAL(18,2)) AS 用户实际支付净成交金额,
CAST(REPLACE(`追投调控消耗`, ',', '') AS DECIMAL(18,2)) AS 追投消耗,
CAST(REPLACE(`追投调控展示次数`, ',', '') AS DECIMAL(18,2)) AS 追投展现,
CAST(REPLACE(`追投调控点击次数`, ',', '') AS DECIMAL(18,2)) AS 追投点击,
CAST(REPLACE(`追投调控成交订单数`, ',', '') AS DECIMAL(18,2)) AS 追投订单数,
CAST(REPLACE(`追投调控成交金额`, ',', '') AS DECIMAL(18,2)) AS 追投成交金额,
CAST(REPLACE(`追投调控用户实际支付金额`, ',', '') AS DECIMAL(18,2)) AS 追投用户实际支付金额,
CAST(REPLACE(`视频播放数`, ',', '') AS DECIMAL(18,2)) AS 视频播放数,
CAST(2秒播放率 AS CHAR(10)) AS 2秒播放率,
CAST(3秒播放率 AS CHAR(10)) AS 3秒播放率,
CAST(5秒播放率 AS CHAR(10)) AS 5秒播放率,
CAST(10秒播放率 AS CHAR(10)) AS 10秒播放率,
CAST(REPLACE(`视频完播数`, ',', '') AS DECIMAL(18,2)) AS 视频完播数,
REPLACE(`新增粉丝数`, ',', '') AS 粉丝数,
REPLACE(`视频评论数`, ',', '')  AS 评论数,
REPLACE(`视频点赞数`, ',', '') AS 点赞数,
CAST(REPLACE(`1小时内退款订单数`, ',', '') AS DECIMAL(18,2)) AS 1小时内退款订单数,
CAST(REPLACE(`1小时内退款金额`, ',', '') AS DECIMAL(18,2)) AS 1小时内退款金额,
CAST(REPLACE(`7日结算订单数`, ',', '') AS DECIMAL(18,2)) AS 7日结算订单数,
CAST(REPLACE(`7日结算金额`, ',', '') AS DECIMAL(18,2)) AS 7日结算金额
FROM ods.`ods_千川素材_视频_m`
-- WHERE 整体展现次数>0 OR `整体消耗`>0
UNION ALL
--
-- INSERT INTO dwd.`dwd_千川_素材m`
SELECT
'素材-其他' 来源 ,
`千川UID`,
 抖音UID,
STR_TO_DATE(DATE_FORMAT(时间, '%Y-%m-%d 00:00:00'), '%Y-%m-%d 00:00:00') AS 日期,
STR_TO_DATE(时间, '%Y-%m-%d %H:%i:%s') AS 时间,
'' 素材ID ,
NULL 创建时间,
NULL 投放时间,
'' 全域素材视频类型,
'' 全域素材视频名称,
-- CAST(DATE_FORMAT(时间,"%Y-%m-%d %H:%i:%s") AS DATETIME) 
CAST(0 AS DECIMAL(18,2)) AS 消耗,
CAST(0 AS DECIMAL(18,2)) AS 展现,
CAST(0 AS DECIMAL(18,2)) AS 点击,
CAST(REPLACE(`整体成交订单数`, ',', '') AS DECIMAL(18,2)) AS 订单数,
CAST(REPLACE(`整体成交金额`, ',', '') AS DECIMAL(18,2)) AS 成交金额,
CAST(REPLACE(`用户实际支付金额`, ',', '') AS DECIMAL(18,2)) AS 用户实际支付金额,
CAST(REPLACE(`整体成交订单数`, ',', '') AS DECIMAL(18,2)) AS 净成交订单数,
CAST(REPLACE(`整体成交金额`, ',', '') AS DECIMAL(18,2)) AS 净成交金额,
CAST(REPLACE(`用户实际支付金额`, ',', '') AS DECIMAL(18,2)) AS 用户实际支付净成交金额,
-- CAST(0 AS DECIMAL(18,2)) AS 净成交订单数,
-- CAST(0 AS DECIMAL(18,2)) AS 净成交金额,
-- CAST(0 AS DECIMAL(18,2)) AS 用户实际支付净成交金额,
CAST(0 AS DECIMAL(18,2)) AS 追投消耗,
CAST(0 AS DECIMAL(18,2)) AS 追投展现,
CAST(0 AS DECIMAL(18,2)) AS 追投点击,
CAST(0 AS DECIMAL(18,2)) AS 追投订单数,
CAST(0 AS DECIMAL(18,2)) AS 追投成交金额,
CAST(0 AS DECIMAL(18,2)) AS 追投用户实际支付金额,
CAST(0 AS DECIMAL(18,2)) AS 视频播放数,
'0' 2秒播放率,
'0' 3秒播放率,
'0' 5秒播放率,
'0' 10秒播放率,
0 视频完播数,
0 粉丝数,
0 评论数,
0 点赞数,
0 1小时内退款订单数,
0 1小时内退款金额,
0 7日结算订单数,
0 7日结算金额
FROM ods.ods_千川素材_其他
-- where 整体成交订单数>0
